name: GFWList Auto-Update

on:
  schedule:
    - cron: '0 12 * * *'  # Ежедневно в 12:00 UTC
  workflow_dispatch:

permissions:
  contents: write  # Права на запись

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Актуальная версия

      - name: Download GFWList
        run: curl -sSfL -o gfwlist.txt https://antizapret.prostovpn.org/domains-export.txt

      - name: Download China List
        run: curl -sSfL -o accelerated-domains.china.conf https://fastly.jsdelivr.net/gh/felixonmars/dnsmasq-china-list/accelerated-domains.china.conf

      - name: Convert China List for Russia
        run: |
          awk -F'/' '
            /yandex\.ru/ || /mail\.ru/ || /rbc\.ru/ || /tinkoff\.ru/ || /ozon\.ru/ || /wildberries\.ru/ || /sber\.ru/ {
              print $1"/"$2"/common.dot.dns.yandex.net"
            }
          ' accelerated-domains.china.conf > accelerated-domains.russia.conf

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: gfwlist.txt accelerated-domains.russia.conf
          message: "chore: auto-update lists"
          token: ${{ secrets.GH_TOKEN }}
          
