name: GFWList Auto-Update

on:
  schedule:
    - cron: '0 12 * * *'  # Ежедневно в 12:00 UTC
  workflow_dispatch:

permissions:
  contents: write  # Права на запись

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Актуальная версия

      - name: Download GFWList
        run: curl -sSfL -o gfwlist.txt https://antizapret.prostovpn.org/domains-export.txt

      - name: Download China List
        run: curl -sSfL -o accelerated-domains.china.conf https://fastly.jsdelivr.net/gh/felixonmars/dnsmasq-china-list/accelerated-domains.china.conf

      - name: Replace DNS in China List
        run: sed 's|/[^/]*$|/77.88.8.8|' accelerated-domains.china.conf > accelerated-domains.russia.conf

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: gfwlist.txt accelerated-domains.russia.conf
          message: "chore: auto-update lists"
          token: ${{ secrets.GH_TOKEN }}
          
